### ISSUE TITLE
Can't pass array from the table to component

### ISSUE THREAD

**Issue by lavezzi1** [gurghet/vue-smart-table#22] opened 2016-09-17 07:12 UTC
Hello @gurghet!

I have a component (show-menu) which I put in `<smart-table>`. And menu component inside of show-menu component.

**show-menu component html:**
```
<menu :options="menuOptions"></menu>
```

**show-menu component js:**
```
    props: {
        menuOptions: {
            type: Array,
            required: true,
            default() {
                return [];
            }
        }    
    },
```

**use smart-table on the page:**
```
<smart-table
    :body="body"
    :order-by="['first', 'second', 'third']"
    >
    <show-menu :menu-options="menuOptions" col="third"></show-menu>
</smart-table>

inside of script tag:
var menuOptions = [
    {
        id: 'test',
        text: 'test'
    }, {
        id: 'test1',
        text: 'test1'
    }
];

and in js file of the page:
data: {
    menuOptions: menuOptions
}
```

It doesnt works. No error, just empty menu list. But it works perfect outside of smart-table, for example if I move this line of code outside of smart-table:
```
<show-menu :menu-options="menuOptions" col="third"></show-menu>
```

What I do wrong?

**Comment by gurghet** [comment] 2016-09-17 07:20
Component props are handled specially so there may be some bugs there. Is
the component yours? If so, please try to rename 'menu-options' to a simple
word, like 'options', maybe it's a naming issue. If it's still broken I
will try to reproduce the problem.
Сб, 17 сент. 2016 г. в 9:12, lavezzi1 <notifications@github.com>:

**Comment by lavezzi1** [comment] 2016-09-17 09:19
I tried it doesn't help.

**Comment by lavezzi1** [comment] 2016-09-17 09:57
I tried to reproduce my problem and that's what I got: http://codepen.io/anon/pen/rrLKAy?editors=1010#0 

That's not exactly what I want to accomplish but very very close. Still doesn't works.

**Comment by lavezzi1** [comment] 2016-09-19 05:14
I hope you take a look at it.

**Comment by gurghet** [comment] 2016-09-19 10:33
Thanks for reproducing the problem. Apparently this is not documented well enough.
All the components you put in the smart-table are children of the smart-table. If you want to access properties of the parent smart-table you have to prefix them with $parent.
Furthermore, you are trying to access the parent property 'listItems' which doesn't exist. You should try to access options instead (depending on what you want to do).

    <showmenu :options="$parent.options" col="more"></showmenu>

http://codepen.io/gurghet/pen/dppRvL?editors=1010#0

Please tell me if this works for you. I'll close the issue for now.

**Closed by gurghet** 2016-09-19 10:33 UTC

**Comment by lavezzi1** [comment] 2016-09-19 12:52
@gurghet It works perfect on codepen, I played with it to create more complex components. But unfortunately it doesn't works in my real case, in my project... 

In my 
**show-menu component js:**
I deleted the:
```
            default() {
                return [];
            }
```
Because it doesn't need if I set required value to true right? And now I got the error ` Invalid prop: type check failed for prop "menuOptions". Expected Array, got Undefined. (found in component: <show-menu>)`

**Comment by gurghet** [comment] 2016-09-19 13:09
I'm not able to reproduce this problem. I'm afraid you have to make sure that `menuOptions` actually contains an array at time of initialization.
Would you mind posting the code that contains the data that should initialize `menuOptions`?

**Comment by lavezzi1** [comment] 2016-09-19 13:25
```
<script>
var menuOptions = [
    {
        id: 'test',
        text: 'test'
    }, {
        id: 'test1',
        text: 'test1'
    }
];
</script>

---

and in js file of the page:
data: {
    options: menuOptions
}

---

<show-menu :menu-options="$parent.options" col="third"></show-menu>
```

**Comment by gurghet** [comment] 2016-09-19 13:28
Try to put some example data in options to see if it works

    data: {
      options: [{ name: 'some data' }]
    }

**Comment by lavezzi1** [comment] 2016-09-19 13:32
No, it doesn't.

Only works like if I do: 
`<show-menu :menu-options="[{ id: 'somedata', text: 'some data' }]"></show-menu>`

**Comment by gurghet** [comment] 2016-09-19 13:35
This clearly means the link between the `<show-menu>` component and the root instance is not as simple as it was in the codepen. Try to understand the hierarchy between the smart-table and the instance holding `data: { options: ... }`. Maybe you need another `$parent.$parent`.

**Comment by lavezzi1** [comment] 2016-09-19 13:49
Actually when I wrote `$parent.$parent` it works with 
```
data: {
  options: [{ id: 'somedata', text: 'somedata' }]
}
```

but didn't works:
```
data: {
  options: menuOptions
}
```

What that means?

**Comment by lavezzi1** [comment] 2016-09-19 14:05
I'll try to explain more detailed. And real data.

I have **index.html** page with:

```
<smart-table
    :body="body"
    >
    <smart-table-view-more :list="$list" col="more"></smart-table-view-more>
</smart-table>
```

**index.js**
```
    <script>
        var listItems = [
            {
                id: 'test',
                text: 'test'
            }, {
                id: 'test1',
                text: 'test1'
            }, {
                id: 'test2',
                text: 'test2'
            },  {
                id: 'test3',
                text: 'test3'
            }
        ];
```

**smart-table-view-more component**
```
**js:**
    props: {
        list: {
            type: Array,
            required: true
        }
    },
**html**
<div>
    <span v-el:more-menu>
        More
    </span>
    <menu :trigger="$els.moreMenu" :options="list"></menu>
</div>
```

**menu component**
```
**js**
    props: {
        options: {
            type: Array,
            required: true,
            default() {
                return [];
            }
        },
**html**
<ul>
   <menu-item v-for="o in options"></menu-item>
```

**Comment by lavezzi1** [comment] 2016-09-19 14:14
Lol I just played with that and typed:
```:list="$parent.$parent.$parent.$parent.$parent.listItems"```

And now it works! But it looks ugly. Can I make more readable and maintainable?

**Comment by gurghet** [comment] 2016-09-19 14:34
Well at this point it's not a smart-table issue anymore. But I would suggest you to revisit how you structured your app and make it less nested. If that isn't practical maybe create intermediate variables along the chain.

**Comment by gurghet** [comment] 2016-09-20 16:31
Actually I think in this case it would be good practice to work with events instead of straight variables since you struggle to figure out the hierarchy of the application.
